const quotes = [
    '<p>"Sorry! I don’t want any adventures, thank you. Not Today. Good morning! But please come to tea – any time you like! Why not tomorrow? Good bye!"</p><footer>Bilbo Baggins, The Hobbit, Unexpected Party</footer>',
    '<p>"Go back?" he thought. "No good at all! Go sideways? Impossible! Go forward? Only thing to do! On we go!"</p><footer>Bilbo Baggins, The Hobbit, Riddles in the Dark</footer>',
    '<p>"Now I know what a piece of bacon feels like when it is suddenly picked out of the pan on a fork and put back on the shelf!"</p><footer>Bilbo Baggins, The Hobbit, Out of the Frying-pan Into the Fire</footer>',
    '<p>“I came from the end of bag, but no bag went over me. I am the friend of bears and the guest of eagles. I am Ring-winner and Luckwearer; and I am Barrel-rider.”</p><footer>Bilbo Baggins, The Hobbit, Inside Information</footer>',
    '<p>“I don’t know half of you half as well as I should like; and I like less than half of you half as well as you deserve.”</p><footer>Bilbo Baggins, The Fellowship of the Ring, A Long-expected Party</footer>',
    '<p style="white-space:pre">"All that is gold does not glitter,<br>Not all those who wander are lost;<br>The old that is strong does not wither,<br>Deep roots are not reached by the frost.<br>From the ashes a fire shall be woken,<br>A light from the shadows shall spring;<br>Renewed shall be blade that was broken,<br>The crownless again shall be king."</p><footer>Poem in honour of Aragorn by Bilbo Baggins, The Fellowship of the Ring, Stride</footer>',
    '<p>“Short cuts make delays, but inns make longer ones.”</p><footer>Frodo Baggins, The Fellowship of the Ring, A Short Cut to Mushrooms</footer>',
    '<p>“It is useless to meet revenge with revenge: it will heal nothing.”</p><footer>Frodo Baggins, The Return of the King, The Scouring of the Shire</footer>',
    '<p>“I tried to save the Shire, and it has been saved, but not for me. It must often be so, Sam, when things are in danger: some one has to give them up, lose them, so that others may keep them.”</p><footer>Frodo Baggins, The Return of the King, The Grey Havens</footer>',
    '<p>“I am glad you are here with me. Here at the end of all things, Sam.”</p><footer>Frodo Baggins, The Return of the King, Mount Doom</footer>',
    '<p>“It’s a dangerous business, Frodo, going out of your door,” he used to say. ‘You step into the Road, and if you don’t keep your feet, there is no telling where you might be swept off to.”</p><footer>Frodo quoting Bilbo, The Fellowship of the Ring, Three is Company</footer>',
    '<p>“I will take the Ring, though I do not know the way.”</p><footer>Frodo Baggins, The Fellowship of the Ring, The Council of Elrond</footer>',
    '<p>“I should like to leave the Shire, if I could – though there have been times when I thought the inhabitants too stupid and dull for words, and have felt that an earthquake or an invasion of dragons might be good for them. But I don’t feel like that now. I feel that as long as the Shire lies behind, safe and comfortable, I shall find wandering more bearable: I shall know that somewhere there is a firm foothold, even if my feet cannot stand there again.”</p><footer>Frodo Baggins, The Fellowship of the Ring, The Shadow of the Past</footer>',
    '<p>"He that breaks a thing to find out what it is has left the path of wisdom."</p><footer>Gandalf the Grey, Council of Elrond, The Fellowship of the Ring</footer>',
    '<p>"I am looking for someone to share in an adventure that I am arranging, and it\'s very difficult to find anyone."</p><footer>Gandalf the Grey, An Unexpected Party, The Hobbit</footer>',
    '<p>“Deserves it! I daresay he does. Many that live deserve death. And some that die deserve life. Can you give it to them? Then do not be too eager to deal out death in judgement. For even the very wise cannot see all ends. I have not much hope that Gollum can be cured before he dies, but there is a chance of it. And he is bound up with the fate of the Ring. My heart tells me that he has some part to play yet, for good or ill, before the end; and when that comes, the pity of Bilbo may rule the fate of many – yours not least.”</p><footer>Gandalf the Grey, The Shadow of the Past, The Fellowship of the Ring</footer>', 
    '<p>"You cannot pass," he said. The orcs stood still, and a dead silence fell. "I am a servant of the Secret Fire, wielder of the flame of Anor. You cannot pass. The dark fire will not avail you, flame of Udûn. Go back to the Shadow! You cannot pass."</p><footer>Gandalf the Grey, The Bridge of Khazad-dûm, The Fellowship of the Ring</footer>',
    '<p>"It is not our part to master all the tides of the world, but to do what is in us for the succour of those years wherein we are set, uprooting the evil in the fields that we know, so that those who live after may have clean earth to till. What weather they shall have is not ours to rule."</p><footer>Gandalf the White, The Last Debate, The Return of the King</footer>',
    '<p>"Many are the strange chances of the world,’ said Mithrandir, ‘and help oft shall come from the hands of the weak when the Wise falter."</p><footer>Gandalf the Grey, Of the Rings of Power and the Third Age, The Silmarillion</footer>',
    '<p>"Moria... You fear to go into those mines. The Dwarves delved too greedily and too deep. You know what they awoke in the darkness of Khazad-dum... shadow and flame."</p><footer>Saruman the White, The Fellowship of the Ring</footer>',
    '<p>"Do you know how the Orcs first came into being? They were elves once, taken by the dark powers, tortured and mutilated. A ruined and terrible form of life. Now... perfected. My fighting Uruk-Hai. Whom do you serve?"</p><footer>Saruman the White, The Fellowship of the Ring</footer>',
    '<p>“Your love for the Halflings\' leaf has clearly slowed your mind.”</p><footer>Saruman the White, The Fellowship of the Ring</footer>',
    '<p>"Concealed within his fortress, the lord of Mordor sees all. His gaze pierces cloud, shadow, earth, and flesh. You know of what I speak, Gandalf: a great Eye, lidless, wreathed in flame."</p><footer>Saruman the White, The Fellowship of the Ring</footer>',
    '<p>"I gave you the chance of aiding me willingly, but you have elected the way of pain."</p><footer>Saruman the White, The Fellowship of the Ring</footer>',
    '<p>Saruman rose to his feet, and stared at Frodo. There was a strange look in his eyes of mingled wonder and respect and hatred. "You have grown, Halfling," he said. "Yes, you have grown very much. You are wise, and cruel. you have robbed my revenge of sweetness, and now I must go hence in bitterness, in debt to your mercy. I hate it and you! Well, I go and I will trouble you no more. But do not expect me to wish you health and long life. You will have neither. But that is not my doing. I merely foretell."</p><footer>Saruman the White, The Return of the King</footer>',
    '<p>"These are Rhosgobel rabbits. I\'d like to see them try!"</p><footer>Radagast the Brown, The Hobbit</footer>',
    '<p>"These are dark spells, Gandalf. Old, and full of hate. Who\'s buried here?"</p><footer>Radagast the Brown, The Hobbit</footer>',
    '<p>"A dark power dwells in there, such as I have never felt before. It is the shadow of an ancient horror. One that can summon the spirits of the dead."</p><footer>Radagast the Brown, The Hobbit</footer>',
    '<p>“Spiders, Gandalf. Giant ones. Some kind of spawn of Ungoliant, or I’m not a wizard. I followed their trail. They came from Dol Guldur.”</p><footer>Radagast the Brown, The Hobbit</footer>',
    '<p>"The Greenwood is sick, Gandalf. A darkness has fallen over it, nothing grows anymore. At least nothing good. The air is foul decay, but worse are the webs."</p><footer>Radagast the Brown, The Hobbit</footer>',
    '<p>"Just give me a minute. Um, Oh! I had a thought and now I’ve lost it. It was, it was was right there, on the tip of my tongue! Oh! It’s not a thought at all! It’s a silly old stick insect."</p><footer>Radagast the Brown, The Hobbit</footer>',

];

function clickFunc(){
    const newNum = Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerHTML = quotes[newNum];
};  